import { Inter } from "next/font/google";

import { TopHeader } from "@/widgets/topHeader";
import { Header } from "@/widgets/header";
import { HeaderMobile } from "@/widgets/headerMobile";
import { Footer } from "@/widgets/footer";

import { QueryProvider } from "./_providers/Query-provider";

import type { Metadata } from "next";

import "@/app/styles/_globals.scss";
import "@/app/styles/_vars.scss";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({ subsets: ["latin"], preload: true });

export const metadata: Metadata = {
    title: "Game Store",
    description: "Generated by create next app",
    icons: {
        icon: ["/favicon.ico?v=4"],
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true} className={inter.className}>
                <QueryProvider>
                    <section className="container">
                        <header className="header">
                            <TopHeader />
                            <Header />
                            <HeaderMobile />
                        </header>
                        {children}
                        <Footer />
                    </section>
                </QueryProvider>
            </body>
        </html>
    );
}
